// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: finanza.proto

package finanza

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaqueteRegistro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete    string  `protobuf:"bytes,1,opt,name=idPaquete,proto3" json:"idPaquete,omitempty"`
	Seguimiento  int64   `protobuf:"varint,2,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
	Tipo         string  `protobuf:"bytes,3,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor        int64   `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Intentos     int64   `protobuf:"varint,5,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Estado       string  `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
	Origen       string  `protobuf:"bytes,7,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino      string  `protobuf:"bytes,8,opt,name=destino,proto3" json:"destino,omitempty"`
	Timestamp    string  `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nombre       string  `protobuf:"bytes,10,opt,name=nombre,proto3" json:"nombre,omitempty"`
	FechaEntrega string  `protobuf:"bytes,11,opt,name=fechaEntrega,proto3" json:"fechaEntrega,omitempty"`
	Ganancia     float32 `protobuf:"fixed32,12,opt,name=ganancia,proto3" json:"ganancia,omitempty"`
}

func (x *PaqueteRegistro) Reset() {
	*x = PaqueteRegistro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finanza_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaqueteRegistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaqueteRegistro) ProtoMessage() {}

func (x *PaqueteRegistro) ProtoReflect() protoreflect.Message {
	mi := &file_finanza_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaqueteRegistro.ProtoReflect.Descriptor instead.
func (*PaqueteRegistro) Descriptor() ([]byte, []int) {
	return file_finanza_proto_rawDescGZIP(), []int{0}
}

func (x *PaqueteRegistro) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

func (x *PaqueteRegistro) GetSeguimiento() int64 {
	if x != nil {
		return x.Seguimiento
	}
	return 0
}

func (x *PaqueteRegistro) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *PaqueteRegistro) GetValor() int64 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *PaqueteRegistro) GetIntentos() int64 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *PaqueteRegistro) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *PaqueteRegistro) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *PaqueteRegistro) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *PaqueteRegistro) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PaqueteRegistro) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PaqueteRegistro) GetFechaEntrega() string {
	if x != nil {
		return x.FechaEntrega
	}
	return ""
}

func (x *PaqueteRegistro) GetGanancia() float32 {
	if x != nil {
		return x.Ganancia
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete string `protobuf:"bytes,1,opt,name=IdPaquete,proto3" json:"IdPaquete,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finanza_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_finanza_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_finanza_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetIdPaquete() string {
	if x != nil {
		return x.IdPaquete
	}
	return ""
}

var File_finanza_proto protoreflect.FileDescriptor

var file_finanza_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x7a, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x7a, 0x61, 0x22, 0xd7, 0x02, 0x0a, 0x0f, 0x70, 0x61, 0x71,
	0x75, 0x65, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65,
	0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x69, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67,
	0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x65, 0x63, 0x68, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x65,
	0x67, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x65, 0x63, 0x68, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6e, 0x61, 0x6e, 0x63,
	0x69, 0x61, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x67, 0x61, 0x6e, 0x61, 0x6e, 0x63,
	0x69, 0x61, 0x22, 0x23, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x64, 0x50,
	0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x64,
	0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x32, 0x4d, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x61, 0x6e,
	0x7a, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0f, 0x69, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x67, 0x61, 0x12, 0x18, 0x2e, 0x66,
	0x69, 0x6e, 0x61, 0x6e, 0x7a, 0x61, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x1a, 0x0c, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x7a, 0x61,
	0x2e, 0x61, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x7a,
	0x61, 0x73, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x7a, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_finanza_proto_rawDescOnce sync.Once
	file_finanza_proto_rawDescData = file_finanza_proto_rawDesc
)

func file_finanza_proto_rawDescGZIP() []byte {
	file_finanza_proto_rawDescOnce.Do(func() {
		file_finanza_proto_rawDescData = protoimpl.X.CompressGZIP(file_finanza_proto_rawDescData)
	})
	return file_finanza_proto_rawDescData
}

var file_finanza_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_finanza_proto_goTypes = []interface{}{
	(*PaqueteRegistro)(nil), // 0: finanza.paqueteRegistro
	(*Ack)(nil),             // 1: finanza.ack
}
var file_finanza_proto_depIdxs = []int32{
	0, // 0: finanza.FinanzaService.informarEntrega:input_type -> finanza.paqueteRegistro
	1, // 1: finanza.FinanzaService.informarEntrega:output_type -> finanza.ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_finanza_proto_init() }
func file_finanza_proto_init() {
	if File_finanza_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_finanza_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaqueteRegistro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finanza_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finanza_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finanza_proto_goTypes,
		DependencyIndexes: file_finanza_proto_depIdxs,
		MessageInfos:      file_finanza_proto_msgTypes,
	}.Build()
	File_finanza_proto = out.File
	file_finanza_proto_rawDesc = nil
	file_finanza_proto_goTypes = nil
	file_finanza_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FinanzaServiceClient is the client API for FinanzaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FinanzaServiceClient interface {
	InformarEntrega(ctx context.Context, in *PaqueteRegistro, opts ...grpc.CallOption) (*Ack, error)
}

type finanzaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinanzaServiceClient(cc grpc.ClientConnInterface) FinanzaServiceClient {
	return &finanzaServiceClient{cc}
}

func (c *finanzaServiceClient) InformarEntrega(ctx context.Context, in *PaqueteRegistro, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/finanza.FinanzaService/informarEntrega", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanzaServiceServer is the server API for FinanzaService service.
type FinanzaServiceServer interface {
	InformarEntrega(context.Context, *PaqueteRegistro) (*Ack, error)
}

// UnimplementedFinanzaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFinanzaServiceServer struct {
}

func (*UnimplementedFinanzaServiceServer) InformarEntrega(context.Context, *PaqueteRegistro) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformarEntrega not implemented")
}

func RegisterFinanzaServiceServer(s *grpc.Server, srv FinanzaServiceServer) {
	s.RegisterService(&_FinanzaService_serviceDesc, srv)
}

func _FinanzaService_InformarEntrega_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaqueteRegistro)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanzaServiceServer).InformarEntrega(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/finanza.FinanzaService/InformarEntrega",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanzaServiceServer).InformarEntrega(ctx, req.(*PaqueteRegistro))
	}
	return interceptor(ctx, in, info, handler)
}

var _FinanzaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "finanza.FinanzaService",
	HandlerType: (*FinanzaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "informarEntrega",
			Handler:    _FinanzaService_InformarEntrega_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finanza.proto",
}
